# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: jkrypto <marvin@42.fr>                     +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2019/09/04 13:24:33 by jkrypto           #+#    #+#              #
#    Updated: 2019/09/04 13:24:36 by jkrypto          ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME=ft_display_file
SRC=src/ft_display_file.c

all:
	gcc $(SRC) -o $(NAME)

clean:
	/bin/rm -f *.o

fclean: clean
	/bin/rm -f $(NAME)
